module:
  admin_toolbar: 0
  adminimal_admin_toolbar: 0
  backstopjs: 0
  basic_auth: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  contact: 0
  cors_ui: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  inline_entity_form: 0
  kint: 0
  link: 0
  maillog: 0
  maxlength: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  qa_shot: 0
  qa_shot_rest_api: 0
  rest: 0
  restui: 0
  serialization: 0
  simpletest: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  toolbar_anti_flicker: 0
  update: 0
  user: 0
  views_ui: 0
  webprofiler: 0
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  bootstrap: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
